name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - server
  # pull_request:
  #   branches:
  #     - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Adjust based on your project

      - name: Restore Dependencies
        run: dotnet restore ecommerce.API/src/App/E-Commerce.App

      - name: Build
        run: dotnet build ecommerce.API/src/App/E-Commerce.App --no-restore --configuration Release

      # - name: Run Tests
      #   run: dotnet test --no-build --configuration Release --verbosity normal

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/server'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Publish Project
        run: dotnet publish ecommerce.API/src/App/E-Commerce.App -c Release -o ./publish

      - name: Upload to Somee.com via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /www.e-commerce-test.somee.com/